### ISSUE TITLE
[Metaissue] Complete new Geocoder

### ISSUE THREAD

**Issue by andrewxhill** [CartoDB/data-services#44]
- [x] Organize admin0 data
- [x] Organize admin0 synonyms
- [x] Release new admin0 plpgsql
- [x] Organize admin1 data
- [ ] Organize admin1 synonyms
- [ ] Release new admin1 plpgsql
- [x] Organize postal code polygons
- [x] Release new postal code polygon plpgsql
- [ ] Organize postal code points
- [ ] Release new postal code points plpgsql
- [ ] Organize new named places dataset
- [ ] Release new named places plpgsql
- [x] Update IP Address dataset from Maxmind
- [x] Update IP Address plpgsql
- [ ] Update coverage tables used by the UI
